config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.


  resources :articles do
    resources :comments
  end
  # Defines the root path route ("/")
  root "articles#index"
  post "articles/:id/toggle", to: "articles#toggle"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :name, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :toggle]

  def index
    @articles = Article.all.load_async
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  def toggle
    @article.update(completed: params[:completed])
    render json: { message: 'Success' }
  end

  private

  def set_article
    @article = Article.find_by(id: params[:id])
  end

  def article_params
    params.require(:article).permit(:name, :article_type)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article, except: [:show]

  def new
    @comment = @article.comments.build
  end

  def create
    @comment = @article.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @article, notice: 'Comment was successfully created.' }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { redirect_to article_url(5) }
      end
    end
  end

  def show
    @comment = Comment.find_by(id: params[:id])
  end

  def edit
    @comment = @article.comments.find_by(id: params[:id])
  end

  def update
    @comment = @article.comments.find_by(id: params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @article, notice: 'Comment was successfully updated.' }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@comment, partial: 'comments/comment', locals: { comment: @comment }) }
      end
    end
  end

  def destroy
    @comment = @article.comments.find_by(id: params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.turbo_stream
    end
  end

  private

  def set_article
    @article = Article.find_by(id: params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.erb
<div class="border border-gray-300 row py-2 justify-content-center align-items-center">
  <div class="col-1">
    <div class="block" data-controller="user-toggle">
      <%= form_with(model: article, class:"text-lg inline-block my-3 w-72") do |form| %>
      <%= form.check_box :completed,
                    data: {
                      id: article.id,
                      action: "user-toggle#toggle",
                      id: article.id
                    },
                    class: "mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500" %>
        
      <% end %>
    </div>
  </div>
  <div class="col-2"><%= article.id %></div>
  <div class="col-3 text-capitalize"  data-controller="user-click" data-user-click-target="name" data-action="click->user-click#getArticleName"><%= article.name %></div>
  <div class="col-3"><%= article.article_type %></div>
  <div class="col-3 d-flex">
    <%= link_to "View", article, data: { turbo_frame: "index_page" }, class: "text-secondary mx-1"%>
    <%= link_to "Edit",  edit_article_path(article),data: { turbo_frame: "index_page" },class: "text-secondary mx-1"%>
    <%= button_to 'Delete', article_path(article), method: :delete,data: { turbo_frame: "index_page" }, class: 'link-style-button mx-1' %>
  </div>
</div>

app/views/articles/_form.html.erb
<div id="article_form">
<div class="border  shadow p-3 my-2 bg-light">
  <%= form_with(model: article) do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name,class:"form-control mb-2" %>
    <% article.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :article_type %><br>
    <%= form.text_field :article_type,class:"form-control mb-2" %><br>
    <% article.errors.full_messages_for(:article_type).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  <% end %>
</div>
</div>

app/views/articles/create.turbo_stream.erb
<%= turbo_stream.prepend "articles" do %>
  <%= render "article", article: @article %>
<% end %>
<%= turbo_stream.replace "article_form" do %>
  <%= render "form", article: Article.new %>
<% end %>

app/views/articles/edit.html.erb
<%= turbo_frame_tag "index_page" do %>
  <div class="text-secondary container-fluid bg-light px-5 py-3 d-flex justify-content-between align-items-center">
    <div>
      <%= link_to "Back to Articles", "/articles" , class:"text-secondary text-decoration-none" %>
      <h2 class="text-capitalize"><%= @article.name %></h2>
    </div>   
  </div>
  <div class="mx-3">
    <%= render "form", article: @article %>
  </div>
<% end %>

app/views/articles/index.html.erb
<%= turbo_frame_tag "index_page" do %>
  <div class="text-secondary container-fluid bg-light px-5 py-3 d-flex justify-content-between align-items-center">
    <h2 class="">Articles</h2> 
    <%= link_to "New Article", new_article_path ,data: { turbo_frame: "index_page"}, class:"btn btn-sm btn-secondary" %>
  </div>
   
  <% if @articles.present?%>
  <div class="mx-3 my-1 p-3">
    <div class="row px-1">
      <div class="col-3">
        <h6>Id</h6>
      </div>
      <div class="col-3">
        <h6>Name</h6>
      </div>
      <div class="col-3">
        <h6>Article Type</h6>
      </div>
      <div class="col-3">
        <h6>Controls</h6>
      </div>
    </div>

    <div id="articles">
      <%= render @articles%>
    </div>
  <% else %>
    <div class=" mt-5 text-center text-secondary ">
    <h5 style=" border-style:dotted; display:inline;" class="p-3">There is no articles yet.  <%= link_to "New Article", new_article_path ,data: { turbo_frame: "index_page"}, class:"text-primary" %></h5>
    </div>
  <%end%>
  </div>
<% end %>

app/views/articles/new.html.erb
<%= turbo_frame_tag "index_page" do %>
  <div class="text-secondary container-fluid bg-light px-5 py-3 d-flex justify-content-between align-items-center">
    <div>
      <%= link_to "Back to Articles", "/articles" , class:"text-secondary text-decoration-none" %>
      <h3>New Article</h3>
    </div>   
  </div>
  <div class="mx-3">
    <%= render "form", article: @article %>
  </div>
<% end %>

app/views/articles/show.html.erb
<%= turbo_frame_tag "index_page" do %>
  <div class="text-secondary container-fluid bg-light px-5 py-3 d-flex justify-content-between align-items-center">
    <div>
      <%= link_to "Back to Articles", "/articles" , class:"text-secondary text-decoration-none" %>
      <h2 class="text-capitalize"><%= @article.name %></h2>
    </div>
    <div class="d-flex justify-content-between">
      <%= link_to "Edit Article", edit_article_path(@article) , class:"btn btn-secondary mx-2 btn-sm"%>
      <%= button_to 'Delete Article', article_path(@article), method: :delete, class: 'btn btn-secondary mx-2 btn-sm' %>
    </div>

  </div>
    <div class="p-2">
    <p class="mx-5" >Article Type: <%= @article.article_type %></p>
  </div>


  <div class="mx-5">
    <h4>Comments</h4> 
    <div id="comments">
      <%= render partial: 'comments/comment', collection: @article.comments, as: :comment %>
    </div>
    <%= turbo_frame_tag "comments_form" do %>
      <h4>Add a comment:</h4>
      <%= render 'comments/form', comment: Comment.new, article: @article %>
    <%end%>
  </div>

<% end %>

app/views/comments/_comment.html.erb
<turbo-frame id="comment_<%= comment.id %>">
  <div class="d-flex  border justify-content-between m-1 p-1">
    <div class='d-flex '>
      <div class="mx-2 ">
        <strong>Commenter:</strong>
        <%= comment.commenter %>
      </div>
      <div class="mx-2  ">
        <strong>Comment:</strong>
        <%= comment.body %>
      </div>
    </div>
    <div class="mx-2 d-flex">
      <%= link_to 'Edit', edit_article_comment_path(comment.article, comment),data:{turbo_frame: "comments_form"}, method: :patch , class: 'text-secondary'%>
      <%= button_to 'Delete', article_comment_path(comment.article, comment), method: :delete, class: 'link-style-button mx-1' %>
    </div>
  </div>
</turbo-frame>

app/views/comments/_comment_form_fields.html.erb
<p>
  <%= form.label :commenter %><br>
  <%= form.text_field :commenter, class: "form-control mb-2"  %>
</p>
<p>
  <%= form.label :body %><br>
  <%= form.text_area :body, class: "form-control mb-2" %>
</p>
<p>
  <%= form.submit %>
</p>

app/views/comments/_form.html.erb
<!-- app/views/comments/form.html.erb -->
<%= turbo_frame_tag "comments_form" do %>
  <%= form_with(model: [ @article, @article.comments.build ] ) do |form| %>
    <%= render 'comments/comment_form_fields', form: form %>
  <% end %>
<% end %>

app/views/comments/create.turbo_stream.erb
<!--create.turbo_stream-->
  <%= turbo_stream.prepend "comments" do %>
    <%= render "comment", comment: @comment %>
  <% end %>

  <%= turbo_stream.replace "comments_form" do %>
    <%= render "form", comment: Comment.new %>
  <% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove @comment %>

 

app/views/comments/edit.html.erb
<!-- app/views/comments/edit.html.erb -->
<%= turbo_frame_tag "comments_form" do %>
  <%= form_with(model: [ @article, @comment ] ) do |form| %>
    <%= render 'comments/comment_form_fields', form: form %>
  <% end %>
<% end %>

app/views/comments/update.turbo_stream.erb
<!--create.turbo_stream-->
  <%= turbo_stream.replace @comment do %>
    <%= render "comment", comment: @comment %>
  <% end %>
  
  <%= turbo_stream.replace "comments_form" do %>
    <%= render "form", comment: Comment.new %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewTurbo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg  bg-secondary text-white px-5 py-3 shadow" >
  <a class="navbar-brand text-white" href="#">Admin</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link text-white" href="#">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/articles">Articles</a>
      </li> 
    </ul>
  </div>
</nav>